services:
  # Nginx для раздачи статики Vue
  nginx:
    image: nginx:alpine
    container_name: vue_nginx
    ports:
      - "80:80"       # HTTP
      - "443:443"     # HTTPS (если добавите SSL)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html  # Папка со сборкой Vue
    restart: unless-stopped

