version: "3.8"

services:
  # Генерация DH-параметров (один раз)
  init-dhparams:
    image: certbot/certbot
    restart: "no"
    entrypoint: /bin/sh
    command: -c 'test -f /etc/letsencrypt/ssl-dhparams.pem || openssl dhparam -out /etc/letsencrypt/ssl-dhparams.pem 4096'
    volumes:
      - cert_volume:/etc/letsencrypt

  # Получение SSL-сертификатов (первичное)
  certbot-oneshot:
    image: certbot/certbot
    restart: "no"
    entrypoint: /bin/sh
    command: -c 'test -d /etc/letsencrypt/live/proggyit.ru || certbot certonly --standalone --register-unsafely-without-email -d "proggyit.ru" --rsa-key-size 2048 --agree-tos --force-renewal'
    ports:
      - "80:80"
    volumes:
      - cert_volume:/etc/letsencrypt
    networks:
      - webnet
  # Основной веб-сервер
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
      - cert_volume:/etc/letsencrypt
    depends_on:
      - init-dhparams
      - certbot-oneshot
    networks:
      - webnet
  # Автообновление сертификатов
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    entrypoint: /bin/sh
    command: -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done;'
    volumes:
      - cert_volume:/etc/letsencrypt
      - ./dist:/usr/share/nginx/html

volumes:
  cert_volume:

networks:
  webnet: